name: Workflow Commands
on: [push]

jobs:
  testing-wf-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Setting an error message
        run: echo "::error::Missing semicolon"
      - name: Setting an error message with params
        run: echo "::error title=error title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing semicloln"
      - name: Setting an debug message with params
        run: echo "::debug title=debug title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing semicloln"
      - name: Setting an warning message with params
        run: echo "::warning title=warning title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing semicloln"
      - name: Setting an notice message with params
        run: echo "::notice title=error title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing semicloln"
